

POST  http://localhost:3000/api/empresa
Content-Type: application/json  

{
  "usuario_idusuario": 2,
  "nombre": "Primavera",
  "descripcion": "Florería",
  "ubicacion": { "lat": 37.7749, "lng": -122.4194 }
}















